#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/vscode/bin/linux-x64/072586267e68ece9a47aa43f8c108e0dcbf44622/node" "/home/codespace/.vscode-remote/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"